name: Storybook GitHub Pages

on:
    push:
        branches:
            - trunk

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - name: Checkout
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
              with:
                  ref: trunk

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Build Storybook
              run: npm run storybook:build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook/build
                  force_orphan: true
